# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pipline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies and setup test db
      run: |
        pip install --upgrade pip wheel
        pip install .
    - name: Lint with flake8 / black...
      run: make lint

  unit:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_USER: avracadabra
          POSTGRES_PASSWORD: secret
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        APP_CONFIG: "ci"
      run: make setup-tests
    - name: Test with pytest
      env:
        APP_CONFIG: "ci"
      run: make test
    - name: Coveralls Python
      uses: AndreMiras/coveralls-python-action@v20200413

  integration:
    needs: unit
    steps:
    - uses: actions/checkout@v2
      with:
        repository: avracadabra/QA
        ref: master
    - uses: actions/checkout@v2
      with:
        path: stock
    - uses: actions/checkout@v2
      with:
        repository: avracadabra/api-gateway
        ref: master
        path: api-gateway
    - uses: actions/checkout@v2
      with:
        repository: avracadabra/backend
        ref: master
        path: backend
    - name: Build docker images
      run: |
        ls -la
